/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_ImgSdk_Imaginer */

#ifndef _Included_android_ImgSdk_Imaginer
#define _Included_android_ImgSdk_Imaginer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_ImgSdk_Imaginer
 * Method:    init
 * Signature: ([III)Z
 */
JNIEXPORT jboolean JNICALL Java_android_ImgSdk_Imaginer_init
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     android_ImgSdk_Imaginer
 * Method:    getBoundrys
 * Signature: ()[[J
 */
JNIEXPORT jobjectArray JNICALL Java_android_ImgSdk_Imaginer_getBoundrys
  (JNIEnv *, jobject);

/*
 * Class:     android_ImgSdk_Imaginer
 * Method:    moveBoundry
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_android_ImgSdk_Imaginer_moveBoundry
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     android_ImgSdk_Imaginer
 * Method:    cutOut
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_android_ImgSdk_Imaginer_cutOut
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     android_ImgSdk_Imaginer
 * Method:    showAll
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_android_ImgSdk_Imaginer_showAll
  (JNIEnv *, jobject);

/*
 * Class:     android_ImgSdk_Imaginer
 * Method:    cfinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_ImgSdk_Imaginer_cfinalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
